export const tokens = {
  color: {
    primary:      '#FF5C2C',
    primaryDark:  '#E64A1A',
    primaryLight: '#FFE6DC',
    ink:          '#161513',
    inkMuted:     '#5C5A55',
    inkSubtle:    '#8A8780',
    bg:           '#F4F3EF',
    surface:      '#FFFFFF',
    surfaceAlt:   '#FAFAF7',
    border:       '#E8E6E0',
    borderStrong: '#D4D2CC',
    success:      '#1F9D55',
    successBg:    '#E5F5EC',
    warning:      '#E89313',
    warningBg:    '#FDF1DE',
    danger:       '#D43A2F',
    dangerBg:     '#FBE4E2',
    info:         '#2563EB',
    mapRoute:     '#FF5C2C',
    mapDriver:    '#161513',
    mapDest:      '#FF5C2C',
    darkBg:       '#161513',
    darkSurface:  '#1F1E1B',
  },
  font: {
    display:         'Fraunces_700Bold',
    displayItalic:   'Fraunces_700Bold_Italic',
    body:            'System',
    mono:            'Menlo',
    fallbackDisplay: 'Georgia',
    fallbackBody:    'System',
    fallbackMono:    'Menlo',
  },
  size: {
    display: 32,
    h1:      26,
    h2:      20,
    h3:      17,
    body:    15,
    bodySm:  14,
    caption: 12,
    micro:   10,
  },
  weight: {
    regular:  '400' as const,
    medium:   '500' as const,
    semibold: '600' as const,
    bold:     '700' as const,
  },
  space: {
    xxs: 4, xs: 8, sm: 12, md: 16, lg: 20, xl: 24, xxl: 32, xxxl: 48,
  },
  radius: {
    sm: 8, md: 12, lg: 16, xl: 20, pill: 999,
  },
  shadow: {
    sm:    { shadowColor: '#161513', shadowOpacity: 0.06, shadowRadius: 2,  shadowOffset: { width: 0, height: 1  }, elevation: 1  },
    md:    { shadowColor: '#161513', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4  }, elevation: 4  },
    lg:    { shadowColor: '#161513', shadowOpacity: 0.12, shadowRadius: 28, shadowOffset: { width: 0, height: 12 }, elevation: 8  },
    sheet: { shadowColor: '#161513', shadowOpacity: 0.08, shadowRadius: 24, shadowOffset: { width: 0, height: -4 }, elevation: 12 },
  },
} as const

export type Tokens = typeof tokens
